config/routes.rb
Rails.application.routes.draw do

  get 'students/new'

  devise_for :users
  resources :questions do
    resources :variants
  end
  resource :students
  resources :sections do
    resources :tests
  end

  resources :tests do
    resources :questions
  end

  root 'sections#index'
  post '/sections/new' => 'sections#new'
  post '/groups' => 'students#groups'
  get '/groups' => 'students#groups'
  get '/groups_show' => 'students#groups_show'
  post '/sections/:id/tests/:id/edit' => 'tests#edit'
  post '/sections/:id/tests/new' => 'tests#new'
  post 'block/:id' => 'sections#block'
  post 'unblock/:id' => 'sections#unblock'
  post '/consider' => 'considers#calculate_result'
  get '/consider' => 'considers#calculate_result'
  post '/students/new' => 'students#new'
  post '/signup', to: 'users#create'

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :new, :create]

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(students_params)
    respond_to do |format|
      if @student.save
        format.html {redirect_to section_test_path(students_params[:section_result_name], students_params[:test_result_name])}
        session[:current_user_id] = @student.id
      else
        format.html {render :new}
        format.json {render json: @student.errors, status: :unprocessable_entity}
      end
    end
  end

  def students_params
    params.require(:student).permit(:name, :group, :test_result_name, :section_result_name)
  end

  def groups
    @groups = Student.pluck(:group).uniq
  end

  def show
    if params['section_result_name'].nil?
      @data = Student.where(:group => params['group_name']).pluck(:section_result_name).uniq
      @data = Section.all.where(id: @data).pluck(:name)
      @key = :section_result_name
      @name = t(:sections)
    elsif params['test_result_name'].nil?
      @data = Student.where(:group => params['group_name'], :section_result_name => Section.find_by_name(params['section_result_name']).id).pluck(:test_result_name).uniq
      @data = Test.all.where(id: @data).pluck(:name)
      @key = :test_result_name
      @name = t(:tests)
    else
      Student.where(result: nil).destroy_all
      @data = Student.where(group: params['group_name'],
                            section_result_name: Section.find_by_name(params['section_result_name']).id,
                            test_result_name: Test.find_by_name(params['test_result_name']).id).reverse_order
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/groups.html.erb
<div class="naming-block">
<h1><%=t :groups %></h1>
</div>
<% @groups.each do |group_name|  %>
    <div class="block-element">
      <div class="section_item" style="align-self: center">
        <%= link_to group_name, students_path(group_name: group_name), class: 'section-data' %>
      </div>
    </div>
<% end  %>

app/views/students/new.html.erb
<div class="create_new">
  <%= form_for(@student, :html => {:class => "form-signin"}) do |f| %>
      <div class="form_element" style="padding-bottom: 5px;">
        <div style="text-align: center;font-size: 22px;">
          <%=t :sign_up %>
        </div>
      </div>
      <div class="form_element">
        <%= f.text_field :name, autofocus: true, :class => 'field-input-section-name', :placeholder => t(:student_name), :required => "" %>
      </div>
      <div class="form_element">
        <%= f.text_field :group, autofocus: true, :class => 'field-input-section-name', :placeholder => t(:group), :required => "" %>
      </div>
      <%= f.hidden_field :section_result_name, :value => params[:section] %>
      <%= f.hidden_field :test_result_name, :value => params[:test] %>

      <div class="form_element">
        <input type="submit" name="commit" value=<%= t :start %> class="create_new_section">
      </div>
<% end %>
</div>

app/views/students/show.html.erb
<div class="naming-block">
  <h1><%= @name %></h1>
</div>
<% @data.each do |current_data|  %>
    <div class="block-element">
        <% if @name.nil? %>
            <a class="section-data"><%= current_data.name %></a>
            <span class="section-data result-data"><%= JSON.parse(current_data.result)['current']%>/<%=JSON.parse(current_data.result)['all'] %>,  <%=JSON.parse(current_data.result)['persent'] %>%</span>
            <span class="section-data result-data"><%= current_data.created_at.strftime("%F %R") %></span>
      <% else %>
            <%= link_to current_data, params.merge({@key => current_data}), class: 'section-data' %>
      <% end %>
    </div>
<% end  %>