config/routes.rb
Rails.application.routes.draw do

  get 'students/new'

  devise_for :users
  resources :questions do
    resources :variants
  end
  resource :students
  resources :sections do
    resources :tests
  end

  resources :tests do
    resources :questions
  end

  root 'sections#index'
  post '/sections/new' => 'sections#new'
  post '/groups' => 'students#groups'
  get '/groups' => 'students#groups'
  get '/groups_show' => 'students#groups_show'
  post '/sections/:id/tests/:id/edit' => 'tests#edit'
  post '/sections/:id/tests/new' => 'tests#new'
  post 'block/:id' => 'sections#block'
  post 'unblock/:id' => 'sections#unblock'
  post '/consider' => 'considers#calculate_result'
  get '/consider' => 'considers#calculate_result'
  post '/students/new' => 'students#new'
  post '/signup', to: 'users#create'

end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :name, presence: {message: 'Название секции не может быть пустым'}
  has_many :tests
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  before_action :set_section, only: [:show, :edit, :update, :destroy, :block, :unblock]
  skip_before_action :verify_authenticity_token

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    set_section
    @tests = {}
    @section.tests.each do |test|
      if @tests.has_key?(test.name)
        @tests[test.name][:variants].merge!({test.variant => {id: test.id, questions: test.questions.count}})
      else
        @tests.merge!({test.name => {variants: {test.variant => {id: test.id, questions: test.questions.count}},
                                     come_back: test.come_back, test: test}})
      end
    end
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)
    respond_to do |format|
      if @section.save
        format.html {redirect_to sections_path, notice: 'Section was successfully created.'}
      else
        format.html {render :new}
        format.json {render json: @section.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html {redirect_to @section, notice: 'Section was successfully updated.'}
        format.json {render :show, status: :ok, location: @section}
      else
        format.html {render :edit}
        format.json {render json: @section.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    if @section.blocking
      @section.destroy
      respond_to do |format|
        format.html {redirect_to root_url, notice: 'Section was successfully destroyed.'}
        format.json {head :no_content}
      end
    elsif !@section.blocking
      respond_to do |format|
        format.html {redirect_to root_url, notice: 'Section was not destroyed. Blocking it and destroy again'}
        format.json {head :no_content}
      end
    end
  end

  def block
    set_section.update(blocking: true)
    respond_to do |format|
      format.html {redirect_to root_url, notice: "#{ @section.name } section was successfully blocked."}
      format.json {head :no_content}
    end
  end

  def unblock
    set_section.update(blocking: false)
    respond_to do |format|
      format.html {redirect_to root_url, notice: "#{ @section.name } section was successfully blocked."}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_section
    @section = Section.find_by_id(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def section_params
    params.require(:section).permit(:name)
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<div class="create_new">
  <%= form_for(@section, :html => {:class => "form-horizontal"}) do |f| %>
      <div class="form_element">
        <div style="  text-align: center;font-size: 22px;">
          <%=t :create_section %>
        </div>
      </div>
      <div class="form_element">
        <%= f.text_field :name, class: 'field-input-section-name', placeholder: t(:section_name), autofocus: true %>
      </div>
      <div class="form_element">
        <%= f.submit :class => "create_new_section", :value=> t(:create_section)%>
      </div>
  <% end %>
</div>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', section_path(@section) %>

app/views/sections/index.html.erb
<div class="naming-block">
  <% if user_signed_in? %>

      <h1><%=t :sections %>
        <div class="add_new_element" onclick="$('#add_new_element_selector').click()">+</div>
      </h1>
      <%= button_to '+', new_section_path, :class => 'hided', id: 'add_new_element_selector' %>
  <% else %>
      <h1><%=t :sections %></h1>
  <% end %>

</div>
<div class="row">
  <% unless @sections.nil? %>
      <% @sections.where(blocking: false).each do |section| %>
          <div class="col-xs-12">
            <div class="block-element">
              <a class="link" href="<%= section_path(section) %>">
                <span class="section-data">
                  <%= section.name %>
                </span>
                <a class="link <%= "hided" unless user_signed_in? %>" data-method="block" rel="nofollow" href=<%= "/block/#{section.id}" %>>
                  <span style="color: red;">Block</span>
                </a>
                <span class="badge count-of-tests"><%= section.tests.count %></span>
              </a>
            </div>
          </div>

      <% end %>
  <% end %>
</div>
<% if user_signed_in? %>
    <% unless @sections.where(blocking: true).empty? %>
          <% @sections.where(blocking: true).each do |section| %>
              <div class="col-xs-12">
                <div class="block-element">
                  <a class="link" href="<%= section_path(section) %>">
                <span class="section-data">
                  <%= section.name %>[BLOCKED]
                </span>
                    <a class="link admin_link" rel="nofollow" data-method="unblock" href="/unblock/<%= section.id %>"><span class="admin_link">Unblock</span></a>
                    <a data-confirm="Are you sure?" class="link admin_link" rel="nofollow" data-method="delete" href="/sections/<%= section.id %>"><span class="admin_link">Delete</span></a>
                    <span class="badge count-of-tests"><%= section.tests.count %></span>
                  </a>
                </div>
              </div>
          <% end %>
    <% end %>
<% end %>

app/views/sections/new.html.erb
<%= render 'form' %>

app/views/sections/show.html.erb
<div class="container">
  <div class="naming-block">
    <% if user_signed_in? %>
        <%= button_to '+', new_section_test_path(@section), :class => 'hided', id: 'add_new_element_selector' %>
        <h1><%=t :tests %>
          <div class="add_new_element" onclick="$('#add_new_element_selector').click()">+</div>
        </h1>
    <% else %>
        <h1><%=t :tests %></h1>
    <% end %>
  </div>
  <div class="row">
    <% @tests.each_pair do |test| %>
        <div class="block-element">
          <div class="section_item">
            <a class="link test_run" value="<%= {test[0] => test[1]}.to_json %>"
               href="#">
                <span class="section-data">
                  <%= test[0] %>
                  <% if user_signed_in? %>
                      <a class="link add_question_button" href="#" value="<%= {test[0] => test[1]}.to_json %>">
                        <span class="add_question_link"><%=t :add_question %></span>
                      </a>

                      <a class="link myBtn" id="myBtn" value="<%= {test[0] => test[1]}.to_json %>">
                        <span class="admin_link"><%=t :edit %></span>
                      </a>

                      <a class="link delete_button" value="<%= {test[0] => test[1]}.to_json %>" >
                        <span class="admin_link"><%=t :delete %></span>
                     </a>
                   <% end %>
                  <span class="badge count-of-tests" value="<%= {test[0] => test[1]}.to_json %>" name=<%= test[0] %>>
                  <%= test[1][:variants][1][:questions] %>
                  </span>
                </span>
            </a>
            <%= select_tag test[0], options_for_select(test[1][:variants].keys.map(&:to_s)),
                           class: 'variant_selection', name: test[0], value: {test[0] => test[1]}.to_json %>
            <span class="come_back_icon">
            <% if test[1][:come_back] %>
                &#9668;
            <% else %>
                &#8855;
            <% end %>
          </span>
          </div>
        </div>
        </div>
    <% end %>
    </div>
</div>

<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">×</span>
    <div class="create_new">
      <form id="edit_form" class="form-horizontal" accept-charset="UTF-8" method="post">
        <input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="patch"><input type="hidden">
        <div class="form_element">
          <div style="text-align: center;font-size: 22px;">
            <%=t :edit_test %>
          </div>
        </div>
        <div class="form_element">
          <input class="field-input-section-name" placeholder="Test name" autofocus="autofocus" type="text" value="Name" name="test[name]" id="test_name">
        </div>
        <div class="form_element">
          <div class="edit-test-control">
            <input name="test[come_back]" type="hidden" value="0"><input class="comeback" type="checkbox" value="1" checked="checked" name="test[come_back]" id="test_come_back">
            <label><%=t :to_return %></label>
          </div>
        </div>
        <div class="form_element">
          <input type="submit" name="commit" value="Update Test" class="create_new_section">
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  $("select").change(function () {
//      console.log($(this).attr("name"));
      test_data = JSON.parse($(this).attr('value'));
      variant = $("select[name='" + $(this).attr("name") + "']")[0].selectedIndex + 1;
      $(this).parents(".section_item").children(".count-of-tests").text(Object.values(test_data)[0]['variants'][variant]['questions'])
  });

    $(".myBtn").click(function () {
        test_data = JSON.parse($(this).attr('value'));
        variant = GetVariant(Object.keys(test_data)[0]);
        id = Object.values(test_data)[0]['variants'][variant]['id'];
        $('#edit_form')[0].setAttribute('action',"/sections/" + <%= @section.id %> + "/tests/" + id);
        $('#test_name')[0].setAttribute('value', Object.keys(test_data)[0]);
        $('.modal').css('display', 'block');
    });

    $(".delete_button").click(function () {
        if (confirm("Are you sure?")) {
            test_data = JSON.parse($(this).attr('value'));
            variant = GetVariant(Object.keys(test_data)[0]);
            console.log($(this).val());
            id = Object.values(test_data)[0]['variants'][variant]['id'];
            $(this)[0].setAttribute('href',"/sections/" + <%= @section.id %> + "/tests/" + id);
            $(this)[0].setAttribute('data-method',"delete");
        }
    });

    $(".add_question_button").click(function () {
      test_data = JSON.parse($(this).attr('value'));
      variant = GetVariant(Object.keys(test_data)[0]);
      console.log($(this).val());
      id = Object.values(test_data)[0]['variants'][variant]['id'];
      $(this)[0].setAttribute('href',"/sections/" + <%= @section.id %> + "/tests/" + id + '/edit');
    });

    $(".test_run").click(function () {
        console.log($(this));
       test_data = JSON.parse($(this).attr('value'));
       variant = GetVariant(Object.keys(test_data)[0]);
       console.log($(this).val());
       id = Object.values(test_data)[0]['variants'][variant]['id'];
        $(this)[0].setAttribute('href',"/students/new?" + "section=" + <%= @section.id %> + "&test=" + id);
    });

    $(".close").click(function () {
        $(".modal").css("display", "none");
    });

    window.onclick = function (event) {
        if ($(event.target).hasClass('modal')) {
            $(".modal").css("display", "none");
        }
    };
    function GetVariant(id) {
        console.log($("[name='" + id + "']")[0].selectedIndex + 1);
        return ($("select[name='" + id + "']")[0].selectedIndex + 1)
    }
</script>